### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by captainhook** [yehudah/Postman-SMTP#1]
Hi Yehuda,

Thank you very much for taking the initiative to fork and apply fixes to the plugin.

Do you plan on maintaining this fork? Whether or not you decide to do so, perhaps we can get some Postman users together from the community to put together some money to ensure some level of maintenance, as I don't see Jason returning (I hope he does!).

We could post on somewhere like Upwork to employ someone to update the plugin for PHP7 compatibility, and perhaps other improvements/additions.

I look forward to reading your thoughts on this.

**Comment by yehudah** [comment]
Hi,

Like you I am a big fan of the plugin, and jason did a great job in each aspect.
For now my plans are to maintain the fork free of charge.
If this fork will become popular and will be harder to maintenance I will consider a premium model for support.

You are more then welcome to publish this fork.

**Comment by captainhook** [comment]
Excellent.
In the meantime, may I suggest updating plugin info in postman-smtp.php:

`/*
 * Plugin Name: Postman SMTP - Fork
 * Plugin URI: https://github.com/yehudah/Postman-SMTP/
 * Description: Email not reliable? Postman is the first and only WordPress SMTP plugin to implement OAuth 2.0 for Gmail, Hotmail and Yahoo Mail. Setup is a breeze with the Configuration Wizard and integrated Port Tester. Enjoy worry-free delivery even if your password changes! Note: This is a fork of the original, for more information please see the github repository.
 * Version: 1.7.2.1
 * Author: Yehuda Hassine
 * Author URI: https://github.com/yehudah
 * License: GPLv2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 */`

**Comment by austingray** [comment]
Would love to see this back in the WP plugin repo. Thanks for taking the initiative here!

**Comment by yehudah** [comment]
Thanks @austingray 
I will do my best to update and fix issues.
