### ISSUE TITLE
No Wizard Connectivity Result and Can't Go Further When Gmail API is the Only Available Option

### ISSUE THREAD

**Issue by scott5598** [yehudah/Postman-SMTP#3]
@yehudah, thank you for your hard work on this. 

Using the approach you suggested, I deactivated the original plugin, overwrite the files and then reactivated it, I installed the most recent plugin code you provide at GitHub on October 13th. While the new code is working and emails are being sent, I have found one apparent issue.

For the code to work on the host I use for several clients that blocks SMTP access to send through Google’s servers, the only option that works is the Gmail API option. While I can manually add the values needed on the Account tab to select this, the Wizard won’t select this option. When I run the Wizard, it counts down through all of the connectivity test options, but doesn’t show Gmail API or any other option as selected after it completes the Connectivity test. Nothing appears below “Your connection settings depend …” If I then click on the Next button, the Connectivity Test flag turns red. The wizard won’t go any further.

If I overwrite your revised code with the code for the original plugin, the Connectivity test completes and indicates Gmail API as the recommended option. I can then complete the next steps in the wizard.
Please let me know if you have any questions or if I can provide any further information.

Once again, thank you for your work on this!
Scott
[Original Postman SMTP Connectivity Test Complete Confirmation Screen 101317.pdf](https://github.com/yehudah/Postman-SMTP/files/1384734/Original.Postman.SMTP.Connectivity.Test.Complete.Confirmation.Screen.101317.pdf)
[Forked Postman SMTP Connectivity Test Complete Confirmation Screen 101417.pdf](https://github.com/yehudah/Postman-SMTP/files/1384735/Forked.Postman.SMTP.Connectivity.Test.Complete.Confirmation.Screen.101417.pdf)

**Comment by yehudah** [comment]
Intresting....

php version ?
plugin version ?

**Comment by scott5598** [comment]
Here is the diagnostic test dump:
OS: Linux ssr15.supercp.com 2.6.32-673.26.1.lve1.4.20.el6.x86_64 #1 SMP Tue Dec 27 17:42:53  EST 2016 x86_64
PHP: Linux 5.5.38 C
PHP Dependencies: iconv=Yes, spl_autoload=Yes, openssl=Yes, sockets=Yes, allow_url_fopen=Yes, mcrypt=Yes, zlib_encode=Yes
WordPress: 4.8.2 en_US UTF-8
WordPress Theme: Divi - SLS Custom
WordPress Plugins: Gravity Forms, All In One SEO Pack Pro, Bloom, Easy Theme and Plugin Upgrades, Elegant Themes Updater, Google Analytics for WordPress by MonsterInsights, Google Authenticator, Google XML Sitemaps, Gravity Forms PayPal Standard Add-On, Post Expirator, Postman SMTP, Redirect for Bloom by Logic Hop, TinyMCE Advanced, UpdraftPlus - Backup/Restore, WooCommerce, Wordfence Security, WP-Optimize
WordPress wp_mail Filter(s): wp_staticize_emoji_for_email
WordPress wp_mail_from Filter(s): wordfence::fixWPMailFromAddress
Postman: 1.7.2
Postman Sender Domain (Envelope|Message): gmail.com | gmail.com
Postman Prevent Message Sender Override (Email|Name): No | No
Postman Active Transport: Gmail API (https:oauth2://www.googleapis.com:443)
Postman Active Transport Status (Ready|Connected): Yes | Yes
Postman Deliveries (Success|Fail): 130 | 2
Let me know if anything else you need.
Scott

**Comment by yehudah** [comment]
Thanks

Can you zip and post a link of the plugin to download ?
I'm suspect I have modified my version and thought it's PHP 7 issue.

**Comment by scott5598** [comment]
Here is the zip file from the site displaying the issue . . . which should match your latest GitHub version . . . but definitely worth checking to make sure you aren't chasing a ghost that I might have created by accident!
Scott
[scott5598 postman-smtp.zip](https://github.com/yehudah/Postman-SMTP/files/1385055/scott5598.postman-smtp.zip)

**Comment by yehudah** [comment]
I have done some change, please download again and test the modified plugin.

**Comment by scott5598** [comment]
Success!  

The wizard now runs as expected and shows the results of the Connectivity test indicating, in this case, that the Gmail API is the selected solution.  I am now able to move through the rest of the wizard steps without any issue.

I ran through the wizard several times and also sent several test email notes which were successfully received.

Thank you for the quick fix . . . and again for your much appreciated efforts to create the new version of this very helpful plugin for all of us in the WordPress community!

Scott

**Comment by yehudah** [comment]
Thanks you for reporting and testing.
