### ISSUE TITLE
Sender info changed after delivery via Google

### ISSUE THREAD

**Issue by LeonNabuurs** [yehudah/Postman-SMTP#7]
Hi,
I use Postman SMTP, in combination with a Google account (Client ID and secret). Works fine, but an 'unrequested feature' shows up. As the sender email address I use a mail address from my website (info@xxx.nl), but appearently somewhere this name is replaced by the Google-account that holds the Client-ID and secret. But that is not what I want!!!
Is there a way to circumvent this email-address-replacement?

**Comment by yehudah** [comment]
Hello, 

This repo is closed, you can see it fro the main screen.

I hope you downloaded the plugin from the official WordPress directory:
https://wordpress.org/plugins/post-smtp/

In the next time you can open a support ticket here:
https://wordpress.org/support/plugin/post-smtp

**For your question, read this:**
https://support.google.com/a/answer/22370?hl=en

**Comment by LeonNabuurs** [comment]
Thnx, worked perfectly!
